export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const LIMPIAR_ALETRTA = 'LIMPIAR_ALETRTA'

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'